/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herenciamulti;

import javax.swing.JOptionPane;

/**
 *
 * @author csuarez25
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        infoInve = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInvest = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        infoDoc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDoc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        infoExt = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtExt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        infoMT = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMT = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        infoCat = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCat = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipos de docentes");
        setLocation(new java.awt.Point(400, 100));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Tipo de Docentes");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel1.setText("Profesor Investigador:");

        infoInve.setText("Ingresar informacion");
        infoInve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoInveActionPerformed(evt);
            }
        });

        txtInvest.setColumns(20);
        txtInvest.setRows(5);
        jScrollPane2.setViewportView(txtInvest);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60)
                        .addComponent(infoInve)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoInve)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Investigador", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel3.setText("Profesor Docente:");

        infoDoc.setText("Ingresar informacion");
        infoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoDocActionPerformed(evt);
            }
        });

        txtDoc.setColumns(20);
        txtDoc.setRows(5);
        jScrollPane3.setViewportView(txtDoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(81, 81, 81)
                        .addComponent(infoDoc)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" Docente", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel5.setText("Profesor Extension:");

        infoExt.setText("Ingresar informacion");
        infoExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoExtActionPerformed(evt);
            }
        });

        txtExt.setColumns(20);
        txtExt.setRows(5);
        jScrollPane4.setViewportView(txtExt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(74, 74, 74)
                        .addComponent(infoExt)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(infoExt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Extension", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel7.setText("Profesor Medio tiempo:");

        infoMT.setText("Ingresar informacion");
        infoMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoMTActionPerformed(evt);
            }
        });

        txtMT.setColumns(20);
        txtMT.setRows(5);
        jScrollPane5.setViewportView(txtMT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(58, 58, 58)
                        .addComponent(infoMT)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(infoMT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medio tiempo", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jLabel10.setText("Profesor Catedratico:");

        infoCat.setText("Ingresar informacion");
        infoCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoCatActionPerformed(evt);
            }
        });

        txtCat.setColumns(20);
        txtCat.setRows(5);
        jScrollPane6.setViewportView(txtCat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(65, 65, 65)
                        .addComponent(infoCat)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(infoCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Catedratico", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoCatActionPerformed
        try {
            catedratico profCat = new catedratico();

            int Id = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la Identificacion:"));
            profCat.setId(Id);

            String nombre = JOptionPane.showInputDialog("Ingresa el Nombre:");
            profCat.setNombre(nombre);

            String apellido = JOptionPane.showInputDialog("Ingresa el Apellido:");
            profCat.setApellido(apellido);

            int horasDeClase = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de clase:"));
            profCat.setHorasClase(horasDeClase);

            String mostrarInfo = profCat.mostrar();

            txtCat.setText(mostrarInfo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo");
        }

    }//GEN-LAST:event_infoCatActionPerformed

    private void infoMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoMTActionPerformed
        try {
            medioTiempo profMT = new medioTiempo();

            int Id = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la Identificacion:"));
            profMT.setId(Id);

            String nombre = JOptionPane.showInputDialog("Ingresa el Nombre:");
            profMT.setNombre(nombre);

            String apellido = JOptionPane.showInputDialog("Ingresa el Apellido:");
            profMT.setApellido(apellido);

            int horasDocen = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de docencia:"));
            profMT.setHorasDocencia(horasDocen);

            int horasAdmin = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas administrativas:"));
            profMT.setHorasAdministrativas(horasAdmin);

            String mostrarInfo = profMT.mostrar();

            txtMT.setText(mostrarInfo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo");
        }

    }//GEN-LAST:event_infoMTActionPerformed

    private void infoExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoExtActionPerformed
        try {
            extension profExten = new extension();

            int Id = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la Identificacion:"));
            profExten.setId(Id);

            String nombre = JOptionPane.showInputDialog("Ingresa el Nombre:");
            profExten.setNombre(nombre);

            String apellido = JOptionPane.showInputDialog("Ingresa el Apellido:");
            profExten.setApellido(apellido);

            String dedicacion = JOptionPane.showInputDialog("Ingresa la dedicación:");
            profExten.setDedicacion(dedicacion);

            int tiempoServicio = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el tiempo de servicio en meses:"));
            profExten.setTiempoServicio(tiempoServicio);

            int horasInvest = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de investigación:"));
            profExten.setHorasInvestigacion(horasInvest);

            int horasDocen = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de docencia:"));
            profExten.setHorasDocencia(horasDocen);

            int horasExten = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de extensión:"));
            profExten.setHorasExtension(horasExten);

            String mostrarInfo = profExten.mostrar();

            txtExt.setText(mostrarInfo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo");
        }

    }//GEN-LAST:event_infoExtActionPerformed

    private void infoInveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoInveActionPerformed
        try {
            investigador profInvest = new investigador();

            int Id = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la Identificacion:"));
            profInvest.setId(Id);

            String nombre = JOptionPane.showInputDialog("Ingresa el Nombre:");
            profInvest.setNombre(nombre);

            String apellido = JOptionPane.showInputDialog("Ingresa el Apellido:");
            profInvest.setApellido(apellido);

            String dedicacion = JOptionPane.showInputDialog("Ingresa la dedicación:");
            profInvest.setDedicacion(dedicacion);

            int tiempoServicio = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el tiempo de servicio en meses:"));
            profInvest.setTiempoServicio(tiempoServicio);

            int horasInvest = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de investigación:"));
            profInvest.setHorasInvestigacion(horasInvest);

            int horasDocen = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de docencia:"));
            profInvest.setHorasDocencia(horasDocen);

            int horasExten = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de extensión:"));
            profInvest.setHorasExtension(horasExten);

            String mostrarInfo = profInvest.mostrar();

            txtInvest.setText(mostrarInfo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo");
        }

    }//GEN-LAST:event_infoInveActionPerformed

    private void infoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoDocActionPerformed
        try {
            docente profDoc = new docente();
            int Id = Integer.parseInt(JOptionPane.showInputDialog("Ingresa la Identificacion:"));
            profDoc.setId(Id);

            String nombre = JOptionPane.showInputDialog("Ingresa el Nombre:");
            profDoc.setNombre(nombre);

            String apellido = JOptionPane.showInputDialog("Ingresa el Apellido:");
            profDoc.setApellido(apellido);

            String dedicacion = JOptionPane.showInputDialog("Ingresa la dedicación:");
            profDoc.setDedicacion(dedicacion);

            int tiempoServicio = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el tiempo de servicio en meses:"));
            profDoc.setTiempoServicio(tiempoServicio);

            int horasInvest = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de investigación:"));
            profDoc.setHorasInvestigacion(horasInvest);

            int horasDocen = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de docencia:"));
            profDoc.setHorasDocencia(horasDocen);

            int horasExten = Integer.parseInt(JOptionPane.showInputDialog("Ingresa las horas de extensión:"));
            profDoc.setHorasExtension(horasExten);

            String mostrarInfo = profDoc.mostrar();

            txtDoc.setText(mostrarInfo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Por favor verificar el tipo de dato ingresado en el campo");
        }

    }//GEN-LAST:event_infoDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton infoCat;
    private javax.swing.JButton infoDoc;
    private javax.swing.JButton infoExt;
    private javax.swing.JButton infoInve;
    private javax.swing.JButton infoMT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtCat;
    private javax.swing.JTextArea txtDoc;
    private javax.swing.JTextArea txtExt;
    private javax.swing.JTextArea txtInvest;
    private javax.swing.JTextArea txtMT;
    // End of variables declaration//GEN-END:variables
}
